# Generated by Django 4.0.3 on 2022-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='name',
            field=models.CharField(max_length=100, unique_for_date='entry_date'),
        ),
    ]
